name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static
          build_command: npm run build-storybook # Optional: Customize your build command

    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}